CREATE TABLE IF NOT EXISTS roles (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL UNIQUE,
description TEXT,
createdAt DATETIME,
updatedAt DATETIME
);


CREATE TABLE IF NOT EXISTS permissions (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL UNIQUE,
description TEXT,
createdAt DATETIME,
updatedAt DATETIME
);


CREATE TABLE IF NOT EXISTS role_permissions (
id INT AUTO_INCREMENT PRIMARY KEY,
roleId INT,
permissionId INT,
createdAt DATETIME,
updatedAt DATETIME,
FOREIGN KEY (roleId) REFERENCES roles(id) ON DELETE CASCADE,
FOREIGN KEY (permissionId) REFERENCES permissions(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
name VARCHAR(255),
createdAt DATETIME,
updatedAt DATETIME
);


CREATE TABLE IF NOT EXISTS user_roles (
id INT AUTO_INCREMENT PRIMARY KEY,
userId INT,
roleId INT,
createdAt DATETIME,
updatedAt DATETIME,
FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (roleId) REFERENCES roles(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS refresh_tokens (
id INT AUTO_INCREMENT PRIMARY KEY,
token VARCHAR(500) NOT NULL,
userId INT,
expiresAt DATETIME,
createdAt DATETIME,
updatedAt DATETIME,
FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);